//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoControlLineaBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkpoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Checkpoint()
        {
            this.TimeControl = new HashSet<TimeControl>();
        }
    
        public int idCheckpoint { get; set; }
        public string description { get; set; }
        public string idLine { get; set; }
        public int status { get; set; }
        public string idEmployee { get; set; }
        public decimal latitud { get; set; }
        public decimal longitud { get; set; }
        public Nullable<int> numberRoute { get; set; }
        public string minArrival { get; set; }
        public string minArrivalMarket { get; set; }
    
        public virtual Line Line { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeControl> TimeControl { get; set; }
    }
}
