//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoControlLineaBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviationRote
    {
        public int idDeviation { get; set; }
        public int idRouteStart { get; set; }
        public int idRouteEnd { get; set; }
        public Nullable<int> numberRoute { get; set; }
        public string idLine { get; set; }
        public Nullable<int> numTypeRoute { get; set; }
    }
}
