//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoControlLineaBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        public string idLine { get; set; }
        public string idPerson { get; set; }
        public string doc { get; set; }
        public int idOwner { get; set; }
    
        public virtual Line Line { get; set; }
        public virtual Person Person { get; set; }
    }
}
