//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoControlLineaBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public string idLine { get; set; }
        public int idPlace { get; set; }
        public int idRoute { get; set; }
        public decimal latitud { get; set; }
        public decimal logintud { get; set; }
        public Nullable<int> numberRoute { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> numPoint { get; set; }
        public Nullable<int> numTypeRoute { get; set; }
    
        public virtual Line Line { get; set; }
        public virtual Place Place { get; set; }
    }
}
