//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoControlLineaBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sanction()
        {
            this.SanctionEmployee = new HashSet<SanctionEmployee>();
        }
    
        public int idSanction { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string idLine { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Line Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanctionEmployee> SanctionEmployee { get; set; }
    }
}
